= 환경 변수

:project-name: tutorial-app

환경 변수는 앱을 안전하고 유연하며 체계적으로 유지합니다. 컨테이너에 환경 변수를 전달하는 방법을 살펴보겠습니다.

== 컨테이너와 함께 환경 변수 사용

Quarkus를 사용하여 만든 Java 애플리케이션을 편집해 보겠습니다.
*tutorial-app* 디렉터리에서 아래 명령어를 수행하여 VSCode를 엽니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
code .
----

이제 `src\main\java\com\redhat\developers\GreetingResource.java` 클래스를 다음과 같이 편집하세요.

[.console-input]
[source,java]
----
package com.redhat.developers;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import java.util.Optional;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@Path("/hello")
public class GreetingResource {

    @ConfigProperty(name = "config")
    Optional<String> config;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return config.orElse("no config");
    }
}

----

`hello` 만 출력하는 대신 `ConfigProperty` 의 내용을 출력하고, 해당 구성이 존재하지 않으면 `no config` 를 출력한다는 점에 주의하세요.

이제 터미널로 돌아가서 프로젝트를 패키징하세요.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mvn package -DskipTests=true
----

새로운 버전의 애플리케이션을 얻으려면 이미지를 다시 빌드하세요.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
podman build -t my-image .
----

실행 중인 컨테이너를 제거하세요.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
podman rm -f my-container
----

그리고 새로운 것을 실행합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
NUM=$(echo $USER | grep -oP '\d{2}$')
podman run -d --name my-container -p 80"$NUM":8080 my-image
----

이제 애플리케이션을 다음과 같이 호출해 보겠습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:80"$NUM"/hello
----

이제 다음과 같은 출력이 나왔습니다.

[.console-output]
[source,text]
----
no config
----

`no config` 가 출력된 이유는 우리가 실제로 환경 변수를 만들지 않았기 때문에 발생합니다. 수정해 보겠습니다.

Containerfile을 다음과 같이 편집하세요.
(가장 하단에 ENV config=containerfile 라인을 추가합니다)

[.console-input]
[source,docker,subs="+macros,+attributes"]
----
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.18-4

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENV config=containerfile

----

이미지를 다시 빌드하고 컨테이너를 다시 생성합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
podman build -t my-image .
podman rm -f my-container

NUM=$(echo $USER | grep -oP '\d{2}$')
podman run -d --name my-container -p 80"$NUM":8080 my-image
----

그리고 다시 호출해 보겠습니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:80"$NUM"/hello
----

이제 출력은 다음과 같습니다.

[.console-output]
[source,text]
----
containerfile
----

마지막으로 변수의 내용을 바꿔보겠습니다. 먼저 컨테이너를 제거합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
podman rm -f my-container
----

그리고 `podman run` 명령을 실행하면서, `-e` 플래그를 통해 환경 변수에 대한 새 값을 전달하여 컨테이너를 다시 생성합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
NUM=$(echo $USER | grep -oP '\d{2}$')
podman run -d --name my-container -p 80"$NUM":8080 -e config=container my-image
----

그런 다음 애플리케이션을 다시 호출합니다.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl localhost:80"$NUM"/hello
----

변경된 출력은 다음과 같습니다.

[.console-output]
[source,text]
----
container
----
